name: Test (Go)
on:
  push:
  pull_request:

jobs:
  test:
    name: Build&Test
    strategy:
      matrix:
        go: [1.19]
        os: [ubuntu-latest] #[macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Download Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }} #'stable'
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      #- name: Build
      #  #env:
      #  #  GOPROXY: "https://proxy.golang.org"
      #  run: go build .
      - name: Run tests
        #env:
        #  GOPROXY: "https://proxy.golang.org"
        run: go test -v ./...